version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/CodeDeploy-nodejs/
hooks:
  BeforeInstall:
    - location: scripts/nodeinstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
